# Sample .travis.yml for R projects

language: r
sudo: required
warnings_are_errors: true

#notifications:
#  email:
#    on_success: change
#    on_failure: change

before_install:
  - sudo add-apt-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -qq
  - sudo apt-get install -y libv8-dev

r_binary_packages:
  - testthat
  - knitr
  - dplyr
  - classInt
  - maps
  - RColorBrewer
  - ggmap
  - rgdal

#r_github_packages:
#  - jimhester/covr

#after_success:
#  - Rscript -e 'library(covr); coveralls()'

# ggplot2
# raster
